### PR TITLE
Add batch voting for proposals

### PR DESCRIPTION
**Pull request by bumi**
The batchVote function accepts an array of proposal ids and votes for
every one.
Normally arrays without fix length are problematic and gas usage can not be
estimated really well. So we need to see how that works or what other
pattern could be used.

### CODE REVIEW

**Comment by fsmanuel** [comment]
@bumi can you rebase? I'm working on `kredits-web` for this. Need to test if it works.

**Comment by bumi** [comment]
done, conflict should be resolved.

**Comment by fsmanuel** [comment]
I need to build the abis again, right?

**Comment by bumi** [comment]
yes, otherwise the JS does not know about the new function. 
`npm run build-json` should do the trick? 

I am not sure if it is good to add the ABI changes in the PR it could easily cause conflicts - similar to a gemfile.lock or similar. - So I think it is better to build them in master? what do you think? how should we handle this in the future?

**Comment by fsmanuel** [comment]
I was wondering the same. I guess if we rebase/merge master before we merge the PR we should commit the ABI changes in the PR.

**Pull request merged**
